
package View;

import Controller.ControllerMaster;
import Controller.CriarClienteController;
import Model.Costureira;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Léo
 */
public class CriarCliente extends javax.swing.JFrame {
    
    private final Costureira costureiraLogada;
    private final CriarClienteController controller;
    
    public CriarCliente() {
        initComponents();
        costureiraLogada = null;
        controller = null;
    }
    
    
    public CriarCliente(Costureira costureiraLogada) {
        ControllerMaster.setIcone(this);
        initComponents();
        
        controller = new CriarClienteController(this);
        controller.atualizaTabela();
        
        this.costureiraLogada = costureiraLogada;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        LabelNome = new javax.swing.JLabel();
        InputNome = new javax.swing.JTextField();
        LabelTelefone = new javax.swing.JLabel();
        InputTelefone = new javax.swing.JTextField();
        LabelEndereco = new javax.swing.JLabel();
        BotaoCriar = new javax.swing.JButton();
        InputEndereco = new javax.swing.JTextField();
        LabelObservacao = new javax.swing.JLabel();
        ScrollPaneObs = new javax.swing.JScrollPane();
        InputObservacao = new javax.swing.JTextArea();
        ScrollPaneClientes = new javax.swing.JScrollPane();
        TabelaClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1010, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(65, 105, 225));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Clientes");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 950, -1));

        LabelNome.setBackground(new java.awt.Color(255, 255, 51));
        LabelNome.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        LabelNome.setText(" Nome*");
        getContentPane().add(LabelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        InputNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InputNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNomeActionPerformed(evt);
            }
        });
        getContentPane().add(InputNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 350, 40));

        LabelTelefone.setBackground(new java.awt.Color(255, 255, 51));
        LabelTelefone.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        LabelTelefone.setText(" Telefone*");
        getContentPane().add(LabelTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        InputTelefone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InputTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(InputTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 350, 40));

        LabelEndereco.setBackground(new java.awt.Color(255, 255, 51));
        LabelEndereco.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        LabelEndereco.setText(" Endereço");
        getContentPane().add(LabelEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        BotaoCriar.setBackground(new java.awt.Color(65, 105, 225));
        BotaoCriar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotaoCriar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoCriar.setText("Criar");
        BotaoCriar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCriarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoCriar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 900, 40));

        InputEndereco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InputEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(InputEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 350, 40));

        LabelObservacao.setBackground(new java.awt.Color(255, 255, 51));
        LabelObservacao.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        LabelObservacao.setText(" Observação");
        getContentPane().add(LabelObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        InputObservacao.setColumns(20);
        InputObservacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InputObservacao.setRows(5);
        ScrollPaneObs.setViewportView(InputObservacao);

        getContentPane().add(ScrollPaneObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 520, 160));

        TabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Telefone", "Endereco", "Observacao"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaClientes.getTableHeader().setReorderingAllowed(false);
        ScrollPaneClientes.setViewportView(TabelaClientes);
        if (TabelaClientes.getColumnModel().getColumnCount() > 0) {
            TabelaClientes.getColumnModel().getColumn(0).setMinWidth(25);
            TabelaClientes.getColumnModel().getColumn(0).setPreferredWidth(30);
            TabelaClientes.getColumnModel().getColumn(0).setMaxWidth(35);
            TabelaClientes.getColumnModel().getColumn(1).setMinWidth(50);
            TabelaClientes.getColumnModel().getColumn(1).setPreferredWidth(100);
            TabelaClientes.getColumnModel().getColumn(1).setMaxWidth(150);
            TabelaClientes.getColumnModel().getColumn(2).setMinWidth(50);
            TabelaClientes.getColumnModel().getColumn(2).setPreferredWidth(100);
            TabelaClientes.getColumnModel().getColumn(2).setMaxWidth(150);
            TabelaClientes.getColumnModel().getColumn(3).setMinWidth(150);
            TabelaClientes.getColumnModel().getColumn(3).setPreferredWidth(200);
            TabelaClientes.getColumnModel().getColumn(3).setMaxWidth(250);
        }

        getContentPane().add(ScrollPaneClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 900, 170));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InputNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNomeActionPerformed

    private void InputTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputTelefoneActionPerformed

    private void InputEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputEnderecoActionPerformed

    private void BotaoCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCriarActionPerformed
        controller.criarCliente();
    }//GEN-LAST:event_BotaoCriarActionPerformed


    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCriar;
    private javax.swing.JTextField InputEndereco;
    private javax.swing.JTextField InputNome;
    private javax.swing.JTextArea InputObservacao;
    private javax.swing.JTextField InputTelefone;
    private javax.swing.JLabel LabelEndereco;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel LabelObservacao;
    private javax.swing.JLabel LabelTelefone;
    private javax.swing.JScrollPane ScrollPaneClientes;
    private javax.swing.JScrollPane ScrollPaneObs;
    private javax.swing.JTable TabelaClientes;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
    
    public void exibirMensagem(String mensagemExibida){
        JOptionPane.showMessageDialog(this, mensagemExibida);
    }
    
    public JTextField getInputEndereco() {
        return InputEndereco;
    }

    public void setInputEndereco(JTextField InputEndereco) {
        this.InputEndereco = InputEndereco;
    }

    public JTextField getInputNome() {
        return InputNome;
    }

    public void setInputNome(JTextField InputNome) {
        this.InputNome = InputNome;
    }

    public JTextArea getInputObservacao() {
        return InputObservacao;
    }

    public void setInputObservacao(JTextArea InputObservacao) {
        this.InputObservacao = InputObservacao;
    }

    public JTextField getInputTelefone() {
        return InputTelefone;
    }

    public void setInputTelefone(JTextField InputTelefone) {
        this.InputTelefone = InputTelefone;
    }

    public JTable getTabelaClientes() {
        return TabelaClientes;
    }

    public void setTabelaClientes(JTable TabelaClientes) {
        this.TabelaClientes = TabelaClientes;
    }


    
}
