
package View;

import Controller.ControllerMaster;
import Controller.CriarServicoController;
import DAO.ServicoDAO;
import DAO.TipoServicoDAO;
import Model.Costureira;
import Model.TipoServico;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

public class CriarServico extends javax.swing.JFrame {

    private CriarServicoController controller;
    private Costureira costureiraLogada;
    
    public CriarServico(Costureira costureiraLogada) {
        ControllerMaster.setIcone(this);
        initComponents();
        controller = new CriarServicoController(this);
        this.costureiraLogada = costureiraLogada;
        
        controller.atualizarComboBoxCliente();
        controller.atualizarComboBoxTipoServico();
        controller.atualizarTabelaServico();
    }
    
    public CriarServico(){
        initComponents();
        controller = null;
        costureiraLogada = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        LabelCliente = new javax.swing.JLabel();
        ComboBoxCliente = new javax.swing.JComboBox<>();
        LabelTipoServico = new javax.swing.JLabel();
        ComboBoxTipoServico = new javax.swing.JComboBox<>();
        LabelValor = new javax.swing.JLabel();
        MoedaValor = new javax.swing.JLabel();
        InputValor = new javax.swing.JTextField();
        MoedaCustoPeca = new javax.swing.JLabel();
        InputCustoPecas = new javax.swing.JTextField();
        LabelCustoPecas = new javax.swing.JLabel();
        LabelObservacao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        InputObservacao = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaServico = new javax.swing.JTable();
        BotaoCriar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1040, 540));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(65, 105, 225));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Serviço");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 950, -1));

        LabelCliente.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        LabelCliente.setText("Cliente*");
        getContentPane().add(LabelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        ComboBoxCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ComboBoxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        ComboBoxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxClienteActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBoxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 220, 40));

        LabelTipoServico.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        LabelTipoServico.setText("Tipo Serviço*");
        getContentPane().add(LabelTipoServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        ComboBoxTipoServico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ComboBoxTipoServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        ComboBoxTipoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTipoServicoActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBoxTipoServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 220, 40));

        LabelValor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        LabelValor.setText("Valor*");
        getContentPane().add(LabelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        MoedaValor.setForeground(new java.awt.Color(102, 102, 102));
        MoedaValor.setText("R$");
        getContentPane().add(MoedaValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));

        InputValor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InputValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputValorActionPerformed(evt);
            }
        });
        getContentPane().add(InputValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 220, 40));

        MoedaCustoPeca.setForeground(new java.awt.Color(102, 102, 102));
        MoedaCustoPeca.setText("R$");
        getContentPane().add(MoedaCustoPeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, -1, -1));

        InputCustoPecas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InputCustoPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputCustoPecasActionPerformed(evt);
            }
        });
        getContentPane().add(InputCustoPecas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 220, 40));

        LabelCustoPecas.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        LabelCustoPecas.setText("Custo Peças");
        getContentPane().add(LabelCustoPecas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        LabelObservacao.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        LabelObservacao.setText("Observação");
        getContentPane().add(LabelObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, -1));

        InputObservacao.setColumns(20);
        InputObservacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InputObservacao.setRows(5);
        jScrollPane1.setViewportView(InputObservacao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 390, 110));

        TabelaServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Cliente", "Status", "Tipo", "Valor", "Custo Pecas", "Data Pedido", "Data Entrega", "Observacao"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TabelaServico);
        if (TabelaServico.getColumnModel().getColumnCount() > 0) {
            TabelaServico.getColumnModel().getColumn(0).setMinWidth(25);
            TabelaServico.getColumnModel().getColumn(0).setPreferredWidth(30);
            TabelaServico.getColumnModel().getColumn(0).setMaxWidth(35);
            TabelaServico.getColumnModel().getColumn(1).setMinWidth(50);
            TabelaServico.getColumnModel().getColumn(1).setPreferredWidth(100);
            TabelaServico.getColumnModel().getColumn(1).setMaxWidth(150);
            TabelaServico.getColumnModel().getColumn(2).setMinWidth(50);
            TabelaServico.getColumnModel().getColumn(2).setPreferredWidth(100);
            TabelaServico.getColumnModel().getColumn(2).setMaxWidth(150);
            TabelaServico.getColumnModel().getColumn(3).setMinWidth(50);
            TabelaServico.getColumnModel().getColumn(3).setPreferredWidth(100);
            TabelaServico.getColumnModel().getColumn(3).setMaxWidth(150);
            TabelaServico.getColumnModel().getColumn(4).setMinWidth(100);
            TabelaServico.getColumnModel().getColumn(4).setPreferredWidth(50);
            TabelaServico.getColumnModel().getColumn(4).setMaxWidth(150);
            TabelaServico.getColumnModel().getColumn(5).setMinWidth(100);
            TabelaServico.getColumnModel().getColumn(5).setPreferredWidth(50);
            TabelaServico.getColumnModel().getColumn(5).setMaxWidth(150);
            TabelaServico.getColumnModel().getColumn(6).setMinWidth(90);
            TabelaServico.getColumnModel().getColumn(6).setPreferredWidth(120);
            TabelaServico.getColumnModel().getColumn(6).setMaxWidth(150);
            TabelaServico.getColumnModel().getColumn(7).setMinWidth(90);
            TabelaServico.getColumnModel().getColumn(7).setPreferredWidth(120);
            TabelaServico.getColumnModel().getColumn(7).setMaxWidth(150);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 900, 200));

        BotaoCriar.setBackground(new java.awt.Color(65, 105, 225));
        BotaoCriar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotaoCriar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoCriar.setText("Criar Serviço");
        BotaoCriar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCriarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoCriar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 900, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxClienteActionPerformed

    private void ComboBoxTipoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTipoServicoActionPerformed
        
        if(getComboBoxTipoServico().getItemCount() > 1 && getComboBoxTipoServico().getSelectedIndex() != 0 && this.isVisible()){
            String tipoServico = (String) getComboBoxTipoServico().getSelectedItem();
            TipoServico ts = TipoServicoDAO.recuperarTipoServicoPorChave(tipoServico);
            getInputValor().setText(String.valueOf(ts.getValor()));
        }
  
    }//GEN-LAST:event_ComboBoxTipoServicoActionPerformed

    private void InputValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputValorActionPerformed

    private void InputCustoPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputCustoPecasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputCustoPecasActionPerformed

    private void BotaoCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCriarActionPerformed
        controller.criarServico();
    }//GEN-LAST:event_BotaoCriarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotaoCriar;
    private javax.swing.JComboBox<String> ComboBoxCliente;
    private javax.swing.JComboBox<String> ComboBoxTipoServico;
    private javax.swing.JTextField InputCustoPecas;
    private javax.swing.JTextArea InputObservacao;
    private javax.swing.JTextField InputValor;
    private javax.swing.JLabel LabelCliente;
    private javax.swing.JLabel LabelCustoPecas;
    private javax.swing.JLabel LabelObservacao;
    private javax.swing.JLabel LabelTipoServico;
    private javax.swing.JLabel LabelValor;
    private javax.swing.JLabel MoedaCustoPeca;
    private javax.swing.JLabel MoedaValor;
    private javax.swing.JTable TabelaServico;
    private javax.swing.JLabel Titulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    
    public void exibirMensagem(String mensagemExibida){
        JOptionPane.showMessageDialog(this, mensagemExibida);
    }
    
    public JComboBox<String> getComboBoxCliente() {
        return ComboBoxCliente;
    }

    public void setComboBoxCliente(JComboBox<String> ComboBoxCliente) {
        this.ComboBoxCliente = ComboBoxCliente;
    }

    public JComboBox<String> getComboBoxTipoServico() {
        return ComboBoxTipoServico;
    }

    public void setComboBoxTipoServico(JComboBox<String> ComboBoxTipoServico) {
        this.ComboBoxTipoServico = ComboBoxTipoServico;
    }

    public void setCostureiraLogada(Costureira costureiraLogada) {
        this.costureiraLogada = costureiraLogada;
    }

    public JTextField getInputCustoPecas() {
        return InputCustoPecas;
    }

    public void setInputCustoPecas(JTextField InputCustoPecas) {
        this.InputCustoPecas = InputCustoPecas;
    }

    public JTextArea getInputObservacao() {
        return InputObservacao;
    }

    public void setInputObservacao(JTextArea InputObservacao) {
        this.InputObservacao = InputObservacao;
    }

    public JTextField getInputValor() {
        return InputValor;
    }

    public void setInputValor(JTextField InputValor) {
        this.InputValor = InputValor;
    }

    public Costureira getCostureiraLogada() {
        return costureiraLogada;
    }

    public JTable getTabelaServico() {
        return TabelaServico;
    }

    public void setTabelaServico(JTable TabelaServico) {
        this.TabelaServico = TabelaServico;
    }

    
}
