/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerMaster;
import Controller.EditarClienteController;
import Model.Cliente;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Léo
 */
public class EditarCliente extends javax.swing.JFrame {
    
    private EditarClienteController controller;
    private Cliente clienteEditar;
    
    public EditarCliente(Cliente clienteEditar ) {
        ControllerMaster.setIcone(this);
        this.clienteEditar = clienteEditar;
        initComponents();
        
        getIdClienteTitulo().setText(clienteEditar.getId() + "");
        
        controller = new EditarClienteController(this);
        controller.preencherInputs();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPaneObs = new javax.swing.JScrollPane();
        InputObservacao = new javax.swing.JTextArea();
        Titulo = new javax.swing.JLabel();
        LabelNome = new javax.swing.JLabel();
        InputNome = new javax.swing.JTextField();
        LabelTelefone = new javax.swing.JLabel();
        InputTelefone = new javax.swing.JTextField();
        LabelEndereco = new javax.swing.JLabel();
        InputEndereco = new javax.swing.JTextField();
        LabelObservacao = new javax.swing.JLabel();
        BotaoConfirmar = new javax.swing.JToggleButton();
        BotaoCancelar = new javax.swing.JToggleButton();
        IdClienteTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(970, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InputObservacao.setColumns(20);
        InputObservacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InputObservacao.setRows(5);
        ScrollPaneObs.setViewportView(InputObservacao);

        getContentPane().add(ScrollPaneObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 520, 160));

        Titulo.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(65, 105, 225));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Clientes");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 830, -1));

        LabelNome.setBackground(new java.awt.Color(255, 255, 51));
        LabelNome.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        LabelNome.setText(" Nome*");
        getContentPane().add(LabelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        InputNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InputNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNomeActionPerformed(evt);
            }
        });
        getContentPane().add(InputNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 350, 40));

        LabelTelefone.setBackground(new java.awt.Color(255, 255, 51));
        LabelTelefone.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        LabelTelefone.setText(" Telefone*");
        getContentPane().add(LabelTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        InputTelefone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InputTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(InputTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 350, 40));

        LabelEndereco.setBackground(new java.awt.Color(255, 255, 51));
        LabelEndereco.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        LabelEndereco.setText(" Endereço");
        getContentPane().add(LabelEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        InputEndereco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InputEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(InputEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 350, 40));

        LabelObservacao.setBackground(new java.awt.Color(255, 255, 51));
        LabelObservacao.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        LabelObservacao.setText(" Observação");
        getContentPane().add(LabelObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        BotaoConfirmar.setBackground(new java.awt.Color(0, 67, 197));
        BotaoConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotaoConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoConfirmar.setText("Confirmar");
        BotaoConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 420, 50));

        BotaoCancelar.setBackground(new java.awt.Color(158, 0, 0));
        BotaoCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotaoCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoCancelar.setText("Cancelar");
        BotaoCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 440, 50));

        IdClienteTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        IdClienteTitulo.setForeground(new java.awt.Color(0, 67, 197));
        IdClienteTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        IdClienteTitulo.setText("15");
        IdClienteTitulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(IdClienteTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InputNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNomeActionPerformed

    private void InputTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputTelefoneActionPerformed

    private void InputEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputEnderecoActionPerformed

    private void BotaoConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConfirmarActionPerformed
        if(controller.editarCliente()){
            exibirMensagem("Cliente atualizado com sucesso!");
            this.dispose();
        }
    }//GEN-LAST:event_BotaoConfirmarActionPerformed

    private void BotaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BotaoCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotaoCancelar;
    private javax.swing.JToggleButton BotaoConfirmar;
    private javax.swing.JLabel IdClienteTitulo;
    private javax.swing.JTextField InputEndereco;
    private javax.swing.JTextField InputNome;
    private javax.swing.JTextArea InputObservacao;
    private javax.swing.JTextField InputTelefone;
    private javax.swing.JLabel LabelEndereco;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel LabelObservacao;
    private javax.swing.JLabel LabelTelefone;
    private javax.swing.JScrollPane ScrollPaneObs;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
    
    public void exibirMensagem(String mensagemExibida){
        JOptionPane.showMessageDialog(this, mensagemExibida);
    }
    
    
    public Cliente getClienteEditar() {
        return clienteEditar;
    }

    public JLabel getIdClienteTitulo() {
        return IdClienteTitulo;
    }

    public JTextField getInputEndereco() {
        return InputEndereco;
    }

    public JTextField getInputNome() {
        return InputNome;
    }

    public JTextArea getInputObservacao() {
        return InputObservacao;
    }

    public JTextField getInputTelefone() {
        return InputTelefone;
    }

    
}
